target_bbox: [149.799, -30.31, 149.80, -30.309]
target_res: 6
date_min: 2022-01-01
date_max: 2022-02-01
target_sources:
  GEE:
    preprocess:
      collection: null
      mask_clouds: null
      mask_probability: null
      reduce: null
      spectral: NDVI
    download:
      bands: NDVI
